apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      # modify the following line with your Docker Hub account name
      - image: mck-developer-services-docker.jfrog.io/argocd-test-image
        name: spring-petclinic
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
