apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: callout
        image: buildpack-deps:curl
        args:
        - /bin/sh
        - -ec
        - curl http://spring-petclinic/oups
      restartPolicy: Never
  backoffLimit: 0
